name: Build Kernel

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          ref: melt-rebase

      - name: Checkout patch
        uses: actions/checkout@v4
        with:
          ref: patch
          path: ss_patch

      - name: Patch sukisu-susfs
        run: |
          mv ss_patch/sukisu-susfs-for-melt.patch ./ss.patch
          git apply ss.patch

      - name: Patch susfs-common
        run: |
          curl -L -o susfs.patch https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-android12-5.10/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch
          chmod +x susfs.patch
          git apply susfs.patch

      - name: Android kernel build
        run: |
          mkdir clang && cd clang
          curl -L -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/428d18d9732aa7ebfcaed87a582d86155db878d4/clang-r416183b.tar.gz
          chmod +x clang.tar.gz
          tar -zvxf clang.tar.gz && cd ..
          export PATH=${{ github.workspace }}/clang/bin:${PATH}
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out mrproper
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out marble_defconfig
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out -j$(nproc --all)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Image-${{ github.ref_name }}
          path: ${{ github.workspace }}/out/arch/arm64/boot/Image


      - name: Push to merge
        run: |
          make mrproper
          rm -rf clang out ss_patch zipper ss.patch susfs.patch
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout merge 2>/dev/null || git checkout -b merge
          git add .
          git commit --allow-empty -m "自动构建-${{ github.ref_name }}"
          git push --force origin merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [ build ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: osm0sis/AnyKernel3
          path: zipper

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: Image-${{ github.ref_name }}

      - name: Patch kpm and pack AK3
        run: |
          curl -L -o kpm https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
          chmod +x kpm && ./kpm
          mv oImage zipper/Image && cd zipper 
          zip -r9 melt-${{ github.ref_name }}-ak3.zip * -x .git README.md *placeholder


      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/zipper/melt-${{ github.run_id }}-ak3.zip
          token: ${{ secrets.BUILD_MELT }}

