name: Build Kernel

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          ref: melt-rebase

      - name: Checkout merge patch
        uses: actions/checkout@v4
        with:
          ref: patch
          path: patch

      - name: Checkout sukisu
        uses: actions/checkout@v2
        with:
          repository: SukiSU-Ultra/SukiSU-Ultra
          ref: susfs-dev
          path: driver/staging

      - name: overwrite
        run: rm -rf driver/staging/kernelsu && mv driver/staging/kernel driver/staging/kernelsu

      - name: Patch sukisu-susfs-dev susfs-common
        run: |
          mv patch/sukisu-susfs-for-melt.patch ss.patch
          curl -L -o 50.patch https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-android12-5.10/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch
          chmod +x ss.patch && chmod +x 50.patch
          git apply ss.patch && git apply 50.patch

      - name: Android kernel build
        run: |
          mkdir clang && cd clang
          curl -L -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/428d18d9732aa7ebfcaed87a582d86155db878d4/clang-r416183b.tar.gz
          chmod +x clang.tar.gz
          tar -zvxf clang.tar.gz && cd ..
          export PATH=${{ github.workspace }}/clang/bin:${PATH}
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out mrproper
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out marble_defconfig
          make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out -j$(nproc --all)

      - name: Download kpm patch
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          preRelease: true
          repository: "SukiSU-Ultra/SukiSU_KernelPatch_patch"
          fileName: "patch_linux"
          out-file-path: "out/arch/arm64/boot"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Patch kpm
        run: |
          cd out/arch/arm64/boot
          chmod +x patch_linux && ./patch_linux
          mv oImage Image

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Image-${{ github.ref_name }}
          path: ${{ github.workspace }}/out/arch/arm64/boot/Image


      - name: Push to merge
        run: |
          cd ${{ github.workspace }}
          make mrproper
          rm -rf clang out ss_patch zipper ss.patch susfs.patch
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout merge 2>/dev/null || git checkout -b merge
          git add .
          git commit --allow-empty -m "自动构建-${{ github.ref_name }}"
          git push --force origin merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [ build ]
    runs-on: ubuntu-22.04
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: Image-${{ github.ref_name }}


      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/melt-sukisu-susfs(${{ github.ref_name }})
          token: ${{ secrets.BUILD_MELT }}

